# CONCORDE v1.0 — configuration Odoo 17 (c) MASITH / Stéphane Moreau
[options]
addons_path = /mnt/extra-addons
admin_passwd = Admin2026!Concorde
data_dir = /var/lib/odoo
db_host = postgres
db_port = 5432
db_user = odoo
db_password = Concorde2026!Prod
db_name = concorde
list_db = False
proxy_mode = True
workers = 2
max_cron_threads = 1
limit_memory_hard = 1073741824
limit_time_cpu = 600
limit_time_real = 1200
smtp_server = False
log_level = info
